//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfChatService
{

    public partial class FriendshipLink
    {
        public int Id { get; set; }
        public int This { get; set; }
        public int With { get; set; }
    
        public virtual User PartA { get; set; }
        public virtual User PartB { get; set; }
    }
}
