//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class Message
    {
        [DataMember]
        public int Id { get; set; }
        public int From { get; set; }
        public int To { get; set; }
        [DataMember]
        public string MessageText { get; set; }
        [DataMember]
        public System.DateTime Date { get; set; }
        [DataMember]
        public bool Seen { get; set; }

        [DataMember]
        public virtual User Sender { get; set; }
        [DataMember]
        public virtual User Receiver { get; set; }
    }
}
